### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by Bloko01** [antoniosarosi/home-cloud#10]
Hola a todos, alguien me podría ayudar, al ejecutar el frontend me salta el siguiente error:

TypeError: Cannot read property 'directories' of undefined
_home-cloud/client/src/components/Dir.js:58_

Dir.fillEntries

 58*|    content.directories.forEach((dir) =>
 59  |       directories.push(<Dirent name={dir} isDirectory key={dir} path={path} />)
 60  |    );

Supongo que sera una tontería pero es que no tengo mucha idea y voy un poco perdido

**Comment by antoniosarosi** [comment]
Seguramente sea porque no está funcionando bien el backend. Antes de poner en marcha el frontend el backend tiene que estar corriendo.

**Comment by Bloko01** [comment]
Ya lo he solucionado, mi versión de node estaba desactualizada y había librerías que no las reconocía. Muchas gracias 😄
