### ISSUE TITLE
Problema al iniciar el windows

### ISSUE THREAD

**Issue by xDanyYT** [antoniosarosi/home-cloud#11]
¡Hola! no sé si es el sitio adecuado para ponerlo o no, pero lo pongo. 
Tengo un problema, y es que cuando inicio el backend me sale este error "Storage path not defined, set a value for HOME_CLOUD_STORAGE environment variable
[nodemon] app crashed - waiting for file changes before starting...". 

En mi carpeta ([Foto de mi carpeta](https://i.imgur.com/HriWlQ8.png) , tengo dos archivos: sample.env y HOME_CLOUD_STORAGE.env, los dos con el mismo contenido: HOME_CLOUD_STORAGE="C:\Users\danie\Desktop\app\home-cloud\server\storage" 

No me inicia, ¿una ayudita?
Gracias.

**Comment by antoniosarosi** [comment]
El fichero se tiene que llamar solo ".env"

**Comment by xDanyYT** [comment]
> El fichero se tiene que llamar solo ".env"

¿Cómo lo llamo solo .env? Le borré todo el nombre y le di a enter y no me deja

**Comment by xDanyYT** [comment]
Ah listo, ya lo hice, muchisimas gracias y gracias por la rápida respuesta.
Un saludo.
