### ISSUE TITLE
Tengo un bug cuando pongo npm run dev

### ISSUE THREAD

**Issue by Juampicosta123** [antoniosarosi/home-cloud#12]
![image](https://user-images.githubusercontent.com/70859962/92412032-a5bb8980-f120-11ea-82e0-14e988f3de84.png)
Como pueden ver cuando npm run dev, se queda en server running on port 5000 y no me deja seguir poniendo nada, soy principiante, alguien me ayuda?
Ya cambie el path y todo y eso si funciona.

**Comment by antoniosarosi** [comment]
Efectivamente, el servidor tiene que estar corriendo, si no quién te responde 😂, los comandos de cd client, npm start tienes que hacerlo en otra terminal aparte

**Comment by Juampicosta123** [comment]
Gracias antonio, soy principiante y me cuesta todavía. Gracias por la rapidez

**Comment by Juampicosta123** [comment]
Lo voy a borrar porque es al pedo
