### ISSUE TITLE
Problema con metodo isDirectory()

### ISSUE THREAD

**Issue by fabriziodsp-ransom** [antoniosarosi/home-cloud#23]
Buenas Antonio, me llamo Fabrizio.
Actualmente me encuentro aplicando ingeniería inversa a tu código con el mero propósito de aprender de él y de adquirir un panorama mas amplio.

Estoy teniendo problemas en el archivo `content.js`. Ubicado en: `/server/src/routes/content.js`.

Basicamente el problema consiste con que la consola constantemente arroja el error "isDirectory() is not a function.". Todo esto sin modificar tu código obviamente. Tuve que "arreglarlo" (con alambres como decimos en Argentina) de la siguiente forma:

```
router.get("/:path?", async (req, res, next) => {
  try {
    const dirPath = processPath(req.params.path);
    const dir = await fs.promises.readdir(dirPath.absolutePath);
    const content = {files: [], directories: []}
    const extensions = [
      ".rar",
      ".png",
      ".jpeg",
      ".jpg",
      ".mp3",
      ".mp4",
      ".wav",
      ".wmv",
      ".zip",
      ".json",
      ".py",
      ".java",
      ".ogg",
      ".html",
      ".docx",
      ".pdf",
      ".odb",
      ".yml",
      ".git",
      ".md",
      ".txt",
      ".js"
    ];

    for await (const dirent of dir) {
     const strlen = dirent.length;

     const extension = dirent.substring(strlen, strlen -4);
     const extension2 = dirent.substring(strlen, strlen -3);
     const extension3 = dirent.substring(strlen, strlen -5);

     // I think it is inefficient
     // Check why Sarosi's method not working
     // CHECKME:

     if (extensions.includes(extension)) {
       content.files.push(dirent);
     } else if(extensions.includes(extension2)) {
       content.files.push(dirent);
     } else if (extensions.includes(extension3)){
       content.files.push(dirent);
     } else {
       content.directories.push(dirent);
     }
    }
    content.directories.sort();
    content.files.sort();

    res.json({path: dirPath.relativePath, content, success: true});
  }
  catch(e) {
    next(e)
  }
});
module.exports = router;
```

La razón por la cual no abro un pull request es porque de verdad me encantaría poder adquirir una explicación de porqué no funciona bien tu código y porque es obvio que el mio es un arreglo provisorio mientras encuentro explicaciones y no una mejoría al tuyo.
Espero tus respuestas porque se que estas ocupadísimo con la universidad. Espero no molestar.

PD: Me cuesta bastante el codigo asincrónico, así que cualquier ayuda es muy muy bienvenida.

**Comment by antoniosarosi** [comment]
Probablemente estás usando una versión antigua de Node,  ```isDirectory``` se añadió en la **v10.10.0**, ejecuta ```node --version``` y lo verás e  seguida.

**Comment by fabriziodsp-ransom** [comment]
Hola de nuevo, he intentado lo que me recomendaste.
La versión actual de NodeJS que tengo es la v10.19.0..
Esto es raro

**Comment by fabriziodsp-ransom** [comment]
**UPDATE** 
Estuve navegando por la documentacion de Node en la sección de File System y he encontrado que el método `isDirectory()` al parecer se encuentra dentro del método `.stat()` (el cuál, por defecto, es asincrónico). Entonces he decidido modificar el código para que en la parte de la iteracion sobre el objeto `dir` utilice `fs.stat()`.

**Lo siguiente es un extracto, corresponde al bucle `for await of..`**

```
for await (const dirent of dir) {
      fs.stat(dirent, (err, stats) => {
        if(err) {
          throw new Error(err);
        }
        if(stats.isDirectory()) {
          content.directories.push(dirent);
        } else {
          content.files.push(dirent);
        }
      });
    }
```
**SPOILER**: _Sigue sin funcionar_

Resuelve con el siguiente error:
`Error: Error: ENOENT: no such file or directory, stat '.atom'`

Pero si quitamos la linea que dice: `throw new Error(err)` (Ya que esto lo que hace es parar la ejecucion del codigo y lanzar el error) nos devuelve:
`TypeError: Cannot read property 'isDirectory' of undefined`

**Comment by antoniosarosi** [comment]
Has puesto mal la ruta del directorio que se usa para almacenar seguramente, el código que hay funciona perfectamente.

**Comment by fabriziodsp-ransom** [comment]
La ruta: `/home/usuario/ `
¿Esta bien?

**Comment by antoniosarosi** [comment]
No, a ver, tienes que poner una ruta que sea un directorio vacío y dónde tengas permisos de lectura y escritura. /home/usuario/almaceniento, por ejemplo. Tienes que crear ese directorio si no existe

**Comment by fabriziodsp-ransom** [comment]
He cambiado la ruta a una carpeta dentro de mi usuario en donde tengo permiso de lectura y escritura y cambié al codigo original de tu repo peeero sigue tirando error, mira:

`TypeError: dirent.isDirectory is not a function`.

Sinceramente no se que pueda ser, tambien lo he probado con el código que envié hace dos comentarios atrás y el error es:

`Error: Error: ENOENT: no such file or directory, stat 'prueba.mp3'`

**Comment by antoniosarosi** [comment]
En qué sistema operativo estás?

**Comment by fabriziodsp-ransom** [comment]
Me encuentro en Ubuntu, estaba pensando que quizá no tengas errores debido a que las dependencias de tu proyecto se encuentran aisladas en un contenedor de docker. Mientras que yo lo hice de nuevo guiandome  por tu código

**Comment by antoniosarosi** [comment]
Las dependencias se tienen que instalar con ````npm i````, si usas docker se instalarán automáticamente, pero el error es una función de la librería estándar no de las dependencias.

**Comment by fabriziodsp-ransom** [comment]
Esto se va a sonar rarísimo. Pero acabo de bajar tu codigo y de seguir las instrucciones que dejaste en el `README.md` (Local para Linux) y me tira el mismo error de antes.

El error es el siguiente:

`Error: isDirectory() is not a function at /server/src/routes/content.js:12`

Reemplacé el código de /server/src/routes/content.js por el que modifiqué yo (el que esta sostenido con alambres) y funciona. Pero no es lo adecuado ni lo que quiero ya que no me permite comprender el porqué del error y como puedo darle mantenibilidad al código a futuro.

¿Alguna idea? No quiero robarte mucho tiempo de la uni o hacerte frustrar sin sentido, de verdad si esto te consume mucho tiempo podés cerrar el thread y yo lo voy a entender.

**Comment by antoniosarosi** [comment]
Mira, más fácil, deja el código original, empieza de cero creando un directorio para almacenamiento y ponme toda la secuencia de comandos que escribes, incluyendo las modificaciones de los archivos **.env**, tal como esta explicado en el README. Puede que te esté equivocando en algún comando.

**Comment by fabriziodsp-ransom** [comment]
Perfecto! Lo haré en breve, solo dame unos minutos que debo hacer algo antes y en cuanto tenga resultados los coloco aquí.

Muchas gracias por la buena onda.
