### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by ElvisGastelum** [antoniosarosi/home-cloud#6]
## Refactor a componentes funcionales
Como idea propongo hacer un refactor a componentes funcionales, yo podria hacer un pull request de eso en unos dias, ya que estoy algo ocupado.
La razon es que deja tus componentes mucho mas limpios y reutilizables.

Dejo un ejemplo de lo que me refiero, chequen mi forma de crear codigo en componentes funcionales: [ejemplo](https://github.com/ElvisGastelum/react-issues-list)

**Comment by antoniosarosi** [comment]
Sí, se puede pasar a componentes funcionales y usar hooks, pero no reescribir todos los componentes de golpe, uno por uno para poder volver atrás por si acaso.

**Comment by Alonely0** [comment]
@antoniosarosi para eso esta GitHub :joy: 
es un control de versiones para ver como ha evolucionado y para revertirlo por si explota.
