### ISSUE TITLE
Conexión externa

### ISSUE THREAD

**Issue by adricape19** [antoniosarosi/home-cloud#8]
Se que es una nube en casa pero y si te pudieras conectar con la ip publica del pc desde otro lugar para guardar tus archivos desde por ejemplo el trabajo.

**Comment by antoniosarosi** [comment]
Puedes, si tienes una IP pública fija, que raro es que alguien lo tenga en su casa, pero suponiendo que es así funciona.

**Comment by ObedMz** [comment]
Se puede, haciendo port forwarding al router al que está conectado el servidor, abrir el puerto por el cual quieres que una red externa pueda comunicarse, y hacer la redirección a la ip local que tiene el servidor y su respectivo puerto.
pero esto implica que cualquiera que sepa la ip y el puerto pueda conectarse remotamente a tu servidor privado. podrías montarte un firewall o alguna protección para que solo tu puedas ingresar.

**Comment by antoniosarosi** [comment]
Esto no tiene que ver con la aplicación en sí, solo con el servidor.
